services:
  registry:
    image: ghcr.io/pesde-pkg/registry:${GIT_COMMIT_HASH:-0.2.3-rc.4}
    env_file:
      - .env
    networks:
      - traefik
    volumes:
      - registry_data:/data

networks:
  traefik:
    external: true

volumes:
  registry_data:
