services:
  registry:
    image: ghcr.io/stefanuk12/registry:${GIT_COMMIT_HASH:-latest}
    env_file:
      - .env
    environment:
      - "ADDRESS=0.0.0.0"
      - "PORT=8080"
      - "DATA_DIR={CWD}/data/data"
      - "FS_STORAGE_ROOT=/data/fs"
      - "COMMITTER_GIT_EMAIL=deploy@${ROOT_DOMAIN}"

      - "ROOT_DOMAIN=${ROOT_DOMAIN}"
      - "INDEX_REPO_URL=${INDEX_REPO_URL}"
      - "GIT_USERNAME=${GIT_USERNAME}"
      - "GIT_PASSWORD=${GIT_PASSWORD}"
      - "READ_NEEDS_AUTH=${READ_NEEDS_AUTH}"
      - "ACCESS_TOKEN=${ACCESS_TOKEN}"
      - "READ_ACCESS_TOKEN=${READ_ACCESS_TOKEN}"
      - "WRITE_ACCESS_TOKEN=${WRITE_ACCESS_TOKEN}"
      - "GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}"
      - "S3_ENDPOINT=${S3_ENDPOINT}"
      - "S3_BUCKET_NAME=${S3_BUCKET_NAME}"
      - "S3_REGION=${S3_REGION}"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "SENTRY_DSN=${SENTRY_DSN}"
    networks:
      - traefik
    volumes:
      - registry_data:/data

networks:
  traefik:
    external: true

volumes:
  registry_data: