services:
  registry:
    image: ghcr.io/stefanuk12/registry:latest
    env_file:
      - .env
    environment:
      - "ADDRESS=0.0.0.0"
      - "PORT=8080"
      - "DATA_DIR={CWD}/data/data"
      - "FS_STORAGE_ROOT=/data/fs"
    networks:
      - traefik
    volumes:
      - registry_data:/data

networks:
  traefik:
    external: true

volumes:
  registry_data: